CREATE TABLE dev_tracks_resources (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    status TEXT NOT NULL,
    url TEXT NOT NULL,
    description TEXT NOT NULL,
    date_completed TIMESTAMP,
    date_created TIMESTAMP DEFAULT now() NOT NULL
)
