CREATE TABLE dev_tracks_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL UNIQUE,
    full_name TEXT NOT NULL,
    password TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);


ALTER TABLE dev_tracks_resources
    ADD COLUMN
        user_id INTEGER REFERENCES dev_tracks_users(id)
        ON DELETE SET NULL;